### ISSUE TITLE
No access to paperback repo

### ISSUE THREAD

**Issue by andyw8** [thoughtbot/goal-oriented-git#24]
I bought the book and wanted to build the latest version. Should I have access to the paperback repo?

**Comment by calebhearth** [comment]
No, paperback is an internal tool we use to build and compile various ebook versions. The latest release should always be available in the repo, however, so that's a problem.

cc @georgebrock

**Comment by calebhearth** [comment]
https://github.com/thoughtbot/goal-oriented-git/issues/25

**Comment by georgebrock** [comment]
@andyw8 The built book is now in the `/release` directory in this repo.

**Comment by andyw8** [comment]
Great, thanks!
